# Generated by Django 3.2.6 on 2021-09-18 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract', models.TextField(max_length=500)),
                ('project_keywords', models.TextField(max_length=500)),
                ('mentor', models.CharField(max_length=100)),
                ('collabrator', models.CharField(default='null', max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 9, 18, 12, 30, 31, 357192))),
                ('completion_date', models.DateField(verbose_name='completion date')),
                ('images', models.ImageField(blank='True', null='True', upload_to=projects.models.upload_location1)),
                ('status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='blank', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank='True', null='True', upload_to=projects.models.upload_location)),
                ('upload_documents', models.FileField(blank='True', null='True', upload_to=projects.models.upload_location)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projects')),
            ],
        ),
    ]
