# Generated by Django 3.2.6 on 2021-09-18 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_date_of_join'),
        ('projects', '0002_alter_projects_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 12, 45, 19, 402686)),
        ),
    ]
