# Generated by Django 3.2.6 on 2021-09-18 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210918_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Employees',
            new_name='Author',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 13, 13, 0, 813306)),
        ),
    ]
