# Generated by Django 3.2.6 on 2021-09-18 07:45

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210918_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('emp', 'emp')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 13, 15, 8, 742341)),
        ),
    ]
