# Generated by Django 3.2.6 on 2021-09-18 10:15

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210918_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('emp', 'emp'), ('bb', 'bb'), ('cc', 'cc')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 45, 54, 346924)),
        ),
    ]
