# Generated by Django 3.2.6 on 2021-09-22 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210921_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_files',
            name='cover',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 11, 41, 939171)),
        ),
    ]
