# Generated by Django 3.2.6 on 2021-09-22 10:27

import datetime
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210922_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_files',
            name='cover',
            field=models.ImageField(blank='True', null='True', upload_to=projects.models.upload_location),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 15, 57, 16, 664113)),
        ),
    ]
