# Generated by Django 3.2.6 on 2021-09-23 05:02

import datetime
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_projects_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_files',
            name='upload_documents',
            field=models.FileField(blank='True', null='True', upload_to=projects.models.upload_location2),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 10, 32, 9, 204678)),
        ),
    ]
