# Generated by Django 3.2.6 on 2021-09-25 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20210925_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 15, 8, 39, 341175)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='work_progress',
            field=models.CharField(choices=[('0', '0%'), ('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], max_length=4),
        ),
    ]
