# Generated by Django 3.2.6 on 2021-09-29 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210929_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='co_author',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 45, 51, 775359)),
        ),
    ]
