# Generated by Django 3.2.6 on 2021-09-29 07:16

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_alter_projects_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 46, 52, 899837)),
        ),
    ]
