# Generated by Django 3.2.6 on 2021-09-29 09:22

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210929_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bb', 'bb'), ('bbbb', 'bbbb')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 14, 52, 4, 742827)),
        ),
    ]
