# Generated by Django 3.2.6 on 2021-09-30 06:26

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20210930_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ff', 'ff'), ('pp', 'pp'), ('ttt', 'ttt'), ('kk', 'kk')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 56, 27, 669104)),
        ),
    ]
