# Generated by Django 3.2.6 on 2021-10-04 17:45

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20210930_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ww', 'ww')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 23, 15, 48, 934596)),
        ),
    ]
