# Generated by Django 3.2.6 on 2021-10-05 05:24

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20211005_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 10, 54, 17, 701026)),
        ),
    ]
