# Generated by Django 3.2.6 on 2021-10-05 09:23

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20211005_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('first', 'first'), ('secound', 'secound'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth')], max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 53, 24, 256973)),
        ),
    ]
