# Generated by Django 3.2.6 on 2021-10-05 10:34

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20211005_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ww', 'ww')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 16, 4, 57, 641994)),
        ),
    ]
