# Generated by Django 3.2.6 on 2021-10-06 10:09

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20211005_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ww', 'ww'), ('emp', 'emp'), ('wdrewf', 'wdrewf')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 15, 39, 50, 330806)),
        ),
    ]
