# Generated by Django 3.2.6 on 2021-10-07 10:24

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20211006_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='co_author',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ww', 'ww'), ('emp', 'emp'), ('wdrewf', 'wdrewf'), ('sgflig', 'sgflig')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 54, 0, 628934)),
        ),
    ]
