# Generated by Django 3.2.6 on 2021-10-07 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20211007_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 16, 35, 40, 483146)),
        ),
    ]
