# Generated by Django 3.2.6 on 2021-10-07 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_alter_projects_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='co_author',
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 17, 23, 55, 606423)),
        ),
    ]
