# Generated by Django 3.2.6 on 2021-09-18 07:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField()),
                ('profile_pic', models.ImageField(upload_to='Users/Profile_pictures')),
                ('Specialization', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6)),
                ('address', models.TextField()),
                ('date_of_join', models.DateTimeField(default=datetime.datetime(2021, 9, 18, 12, 32, 46, 601692))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
