# Generated by Django 3.2.6 on 2021-09-18 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.BigIntegerField()),
                ('profile_pic', models.ImageField(upload_to='Users/Profile_pictures')),
                ('Specialization', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6)),
                ('address', models.TextField()),
                ('date_of_join', models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 45, 54, 346924))),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 45, 54, 346924)),
        ),
    ]
