# Generated by Django 3.2.6 on 2021-09-18 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210918_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_register',
            name='date_of_join',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 49, 21, 957629)),
        ),
    ]
