# Generated by Django 3.2.6 on 2021-09-18 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210918_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 50, 14, 32979)),
        ),
        migrations.AlterField(
            model_name='request_register',
            name='profile_pic',
            field=models.ImageField(upload_to='Users/request'),
        ),
    ]
