# Generated by Django 3.2.6 on 2021-09-29 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Specialization',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 9, 18, 98355)),
        ),
    ]
