# Generated by Django 3.2.6 on 2021-09-29 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request_Register',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 21, 9, 274991)),
        ),
    ]
