# Generated by Django 3.2.6 on 2021-09-29 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 24, 43, 878424)),
        ),
    ]
