# Generated by Django 3.2.6 on 2021-09-29 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20210929_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 24, 59, 996895)),
        ),
    ]
