# Generated by Django 3.2.6 on 2021-09-29 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20210929_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 25, 20, 601155)),
        ),
    ]
