# Generated by Django 3.2.6 on 2021-09-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remark',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 12, 46, 16, 453579)),
        ),
    ]
