# Generated by Django 3.2.6 on 2021-10-07 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_auto_20211006_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 54, 0, 603560)),
        ),
    ]
